### PR TITLE
Small improvements

### PR DESCRIPTION
**Pull request by themouette**
- [X] Add a `-y` option to skip confirmations
- [X]   Copy local install script instead of obscure shortened URL
- [X] Do not store host key

### CODE REVIEW

**Comment by ttlequals0** [comment]
Nice improvements. I will do a review of changes when I get a chance.

**Comment by themouette** [comment]
thank you :)

**Comment by ttlequals0** [comment]
Hello I was testing your changes and it appears as tough the SCP portion is not working properly. Please investigate i have tried multiple time with the same unsuccessful outcome.

Here is my output:
Setting up VPN on 52.90.149.68
Warning: Permanently added '52.90.149.68' (ECDSA) to the list of known hosts.
scp: /home/ubuntu/openvpn-autoinstall.sh: No such file or directory
Error code 5

**Comment by themouette** [comment]
Ooops,

I'll look into it.
Sorry for the convenience.

On Fri, Jul 22, 2016 at 5:07 AM, Dominick Krachtus <notifications@github.com

**Comment by ttlequals0** [comment]
I also noticed some inconsistent behavior with -y. Can you please also review this functionality.

**Comment by ttlequals0** [comment]
Any update on fixes.?

**Comment by themouette** [comment]
I did not take time to check yet, sorry.

**Comment by themouette** [comment]
Rebased onto master.

I fixed the ssh/scp issue.

Can you be more specific about `-y` option inconsistency?
I tried to reproduce but both key and instance deletion behaved as expected.

**Pull request merged**
