### PR TITLE
Fix MTU issue

### PR DESCRIPTION
**Pull request by PastelStorm**
Addressing the MTU issue:
http://community.openvpn.net/openvpn/wiki/271-i-can-ping-through-the-tunnel-but-any-real-work-causes-it-to-lock-up-is-this-an-mtu-problem

### CODE REVIEW

**Comment by ttlequals0** [comment]
Were you seeing this issue?

**Comment by PastelStorm** [comment]
@ttlequals0 Yes

**Comment by ttlequals0** [comment]
Can you provide an example so I can reproduce? I am curious about this.

**Comment by PastelStorm** [comment]
@ttlequals0 
My setup: Mac OS Sierra, Viscosity VPN Client.
I used your script to set up a VPN server and everything was great, except I could only connect to a limited number of websites like Hackernews or AWS web console. Even Google didn't work. So I supposed it was an MTU issue and my guess was correct.

**Pull request merged**
